### ISSUE TITLE
Sherlock by  @_RastaMouse is Deprecated

### ISSUE THREAD

**Issue by r00t-3xp10it** [s1l3nt78/sifter#34]
<H3>I have written a new version of Sherlock</H3>

<b><i>Description:</b></i>
Cmdlet to find missing software patchs for privilege escalation (windows).
This CmdLet continues @_RastaMouse (Deprecated) Module with new 2020 CVE
entrys and a new function to find missing security KB patches by comparing
the list of installed patches againts Sherlock KB List entrys ($dATAbASE).
This Cmdlet also Searchs for 'Unquoted service paths' (EoP vulnerability) and
recursive search for folders with Everyone:(F) permissions ($Env:PROGRAMFILES)
**![Sherlock.ps1 - v1.3.4](https://github.com/r00t-3xp10it/venom/blob/master/aux/sherlock.ps1)**

Iam currently working in a post-exploitation auxiliary (windows)
to help reverse tcp shell's in post-exploitation tasks.
**![MyMeterpreter.ps1 - v1.0.4](https://gist.githubusercontent.com/r00t-3xp10it/68f2c8a17f386c11a3d860e282f21f8e/raw/a2ad72ff975ad74978159a931c57b029bb6a33a2/MyMeterpreter.ps1)**

Have fun ..

**Comment by s1l3nt78** [comment]
Hey! Thanks alot for this!
The Sherlock in sifter is RastaMouse's sherlock, its the sherlock from sherlock-project (https://github.com/sherlock-project/sherlock) and due to sifter being mainly for reconnessaince. I dont think im gonna add this sherlock here. Though the post-exp project i may add.
That being said, i think your version of sherlock would be better suited in my tigershark framework

**Comment by r00t-3xp10it** [comment]
i have not finished the post-exploitation auxiliary yet (allmost done) ..
you can access the <b><i>'BETA'</i></b> version of this project [here](https://github.com/r00t-3xp10it/venom/blob/master/aux/MyMeterpreter.ps1)

**Comment by s1l3nt78** [comment]
Thanks alot! I appreciate it.
